//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiWebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan()
        {
            this.Tour = new HashSet<Tour>();
        }
    
        public string MaKhachSan { get; set; }
        public string MaLoaiKhachSan { get; set; }
        public string TenKhachSan { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string Images { get; set; }
        public string TinhTrang { get; set; }
        public string Mota { get; set; }
        public string Thongtinchitiet { get; set; }
    
        public virtual LoaiKhachSan LoaiKhachSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tour { get; set; }
    }
}
