//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiWebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public string MaLH { get; set; }
        public string ChuDe { get; set; }
        public string TenKH { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
    }
}
