//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiWebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public string MaAnh { get; set; }
        public string Anh { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
    }
}
