//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiWebNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.ChiTietDiaDiem = new HashSet<ChiTietDiaDiem>();
            this.DatTour = new HashSet<DatTour>();
        }
    
        public string Matour { get; set; }
        public string MaLoaiTour { get; set; }
        public string Tentour { get; set; }
        public string Mota { get; set; }
        public string Lichtrinh { get; set; }
        public Nullable<int> Banggia { get; set; }
        public string Thongtinlienquan { get; set; }
        public string Images { get; set; }
        public string MaTinhTrangTour { get; set; }
        public string Diadiemkhoihanh { get; set; }
        public string Thoiluong { get; set; }
        public string MaKhachSan { get; set; }
        public string MaDichVu { get; set; }
        public string Madiadiem { get; set; }
        public string Phuongtien { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public string Lienhe { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDiaDiem> ChiTietDiaDiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTour> DatTour { get; set; }
        public virtual Diadiem Diadiem { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual KhachSan KhachSan { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        public virtual TinhTrangTour TinhTrangTour { get; set; }
    }
}
